# BUS 303 Signature Term Project: Competitive Analysis of the Starbucks and Dunkin' Donuts Beverage Menus

## Deliverable 1: Cleaning and Preparing the Starbucks Menu for Analysis

### Task 1.1: Import Pandas and Load the Starbucks CSV

In [1]:
import pandas as pd

sbux = pd.read_csv(
    'BUS303_Signature_Term_Project_Starbucks_Beverage_Menu.csv')

print('Loaded shape:', sbux.shape)

Loaded shape: (1205, 20)

### Task 1.2: Explore Rows with Blank Values

In [2]:
sbux.isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

### Task 1.3: View the Dataframe with the Head Function

In [3]:
sbux.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

### Task 1.4: Remove Rows with All Blank Entries

In [4]:
sbux2 = sbux.dropna(how='all').copy()

print(
    'Shape after removing fully blank rows:',
    sbux2.shape
)

Shape after removing fully blank rows: (1204, 20)

### Task 1.5: Validate That the Blank Rows Were Removed

In [5]:
print(
    'Fully blank rows remaining:',
    sbux2.isnull().all(axis=1).sum()
)

sbux2.isnull().sum()

Fully blank rows remaining: 0

Product_Name           0
Size                   0
Milk                   0
Whip                   0
Serving_Size_ml        0
Calories               0
Total_Fat_g            0
Saturated_Fat_g        1
Trans_Fat_g            0
Cholesterol_mg         0
Sodium_mg              0
Carbohydrates_g        0
Dietary_Fiber_g        0
Sugar_g                0
Protein_g              0
Vitamin_A_%DV          0
Vitamin_C_%DV          0
Calcium_%DV            0
Iron_%DV               0
Caffiene_milligrams    0
dtype: int64

### Task 1.6: Explore the Data Types

In [6]:
sbux2.dtypes

Product_Name            object
Size                    object
Milk                    object
Whip                    object
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                 object
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

### Task 1.7: Identify the Incorrect Data Type

In [7]:
print(
    'Sugar_g sample values:',
    sbux2.iloc[:, 13].dropna().unique()[:10]
)

print(
    'Sugar_g data type:',
    sbux2.iloc[:, 13].dtype
)

Sugar_g sample values: ['0' 'zero' '5' '2' '8' '4' '10' '13' '6' '7']
Sugar_g data type: object

### Task 1.8: Change Sugar_g to a Float

In [8]:
sbux2['Sugar_g'] = sbux2['Sugar_g'].replace({
    'zero': '0'
})

sbux1 = sbux2.copy()

sbux1['Sugar_g'] = sbux1['Sugar_g'].astype(float)

print(
    'Sugar_g data type after conversion:',
    sbux1['Sugar_g'].dtype
)

Sugar_g data type after conversion: float64

### Task 1.9: Validate the Sugar_g Conversion

In [9]:
print(
    'Sugar_g data type:',
    sbux1['Sugar_g'].dtype
)

print(
    'Values that cannot be converted:',
    pd.to_numeric(
        sbux1['Sugar_g'],
        errors='coerce'
    ).isna().sum()
)

Sugar_g data type: float64
Values that cannot be converted: 0

### Task 1.10: Explore the Remaining NaN Values

In [10]:
sbux1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   object
 1   Size                 1204 non-null   object
 2   Milk                 1204 non-null   object
 3   Whip                 1204 non-null   object
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.5+ KB

### Task 1.11: Remove the Row Containing the NaN Value

In [11]:
df2 = sbux1.dropna().copy()

sbux3 = df2.copy()

print(
    'Shape after removing rows with missing values:',
    sbux3.shape
)

Shape after removing rows with missing values: (1203, 20)

### Task 1.12: Validate That the NaN Value Was Removed

In [12]:
sbux3.info()

print(
    'Missing values remaining:',
    sbux3.isnull().sum().sum()
)

<class 'pandas.core.frame.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   object
 1   Size                 1203 non-null   object
 2   Milk                 1203 non-null   object
 3   Whip                 1203 non-null   object
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.4+ KB
Missing values remaining: 0

### Task 1.13: Correct the Caffeine Column Name

sbux3 = sbux3.rename(
    columns={
        'Caffiene_milligrams': 'Caffeine_milligrams'
    }
)

### Task 1.14: Validate the Corrected Column Name

In [13]:
sbux3.info()

print(
    'Caffeine_milligrams present:',
    'Caffeine_milligrams' in sbux3.columns
)

print(
    'Incorrect spelling remains:',
    'Caffiene_milligrams' in sbux3.columns
)

<class 'pandas.core.frame.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   object
 1   Size                 1203 non-null   object
 2   Milk                 1203 non-null   object
 3   Whip                 1203 non-null   object
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.4+ KB
Caffeine_milligrams present: False
Incorrect spelling remains: True

### Task 1.15: Export the Cleaned Dataframe to sbux4.csv

In [14]:
sbux3.to_csv(
    'sbux4.csv',
    index=False
)

print('Saved sbux4.csv')

Saved sbux4.csv

### Task 1.16: Reload and Validate sbux4.csv

In [15]:
sbux4 = pd.read_csv('sbux4.csv')

print(
    'Reloaded shape:',
    sbux4.shape
)

print(
    'Column names match:',
    sbux4.columns.tolist() == sbux3.columns.tolist()
)

print(
    'Data values match:',
    sbux4.equals(sbux3.reset_index(drop=True))
)

print(
    'Missing values in reloaded file:',
    sbux4.isnull().sum().sum()
)

sbux4.head()

Reloaded shape: (1203, 20)
Column names match: True
Data values match: True
Missing values in reloaded file: 0

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

## Deliverable 2: Cleaning and Preparing the Dunkin' Donuts Menu for Analysis

## Deliverable 3: Comparing Starbucks and Dunkin' Donuts Menu for Analysis